name: Build Containers

on:
  push:
    branches:
      - master

jobs:
  build-php-73:
    name: PHP 7.3
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Production Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: php-7.3/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: defrostedtuna/php-nginx:7.3

      - name: Build Development Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: php-7.3/dev.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: defrostedtuna/php-nginx:7.3-dev

  build-php-74:
    name: PHP 7.4
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Production Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: php-7.4/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: defrostedtuna/php-nginx:7.4

      - name: Build Development Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: php-7.4/dev.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: defrostedtuna/php-nginx:7.4-dev

  build-php-80:
    name: PHP 8.0
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Production Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: php-8.0/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: defrostedtuna/php-nginx:8.0

      - name: Build Development Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: php-8.0/dev.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: defrostedtuna/php-nginx:8.0-dev